version: "3.9"
    
services:    
  bitcoin-balance-notifier:
    build: .
    restart: always
    volumes:
      - db:/db
    environment:
      DISCORD_WEBHOOK: ${DISCORD_WEBHOOK}
      INTERVAL: "10"
      LOG_LEVEL: debug
volumes:
  db: {}
